<?php require('template/header.phtml') ?>


<section class="h-100 " style="background-color: #eee;">
    <div class="container py-3">
        <div class="row d-flex justify-content-center">
            <div class="col">
                <div class="card text-black">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="card-body  mx-md-4">

                                <!--Login Form-->
                                <div class="text-center">
                                    <img src="images/electricbolt.png"
                                         style="width: 100px;" alt="logo">
                                    <h4 class="mt-1 mb-5 pb-1">Welcome to Borrow My Charger!</h4>
                                </div>

                                <form id="login-form"  >
                                    <div class="text-center">
                                    <p>Login to your Account</p>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <input type="email" id="email"  class="form-control"
                                               placeholder="username" ">
                                    </div>

                                    <div class="form-outline mb-4">
                                        <input type="password" id="password"  class="form-control" placeholder="password"
                                                >
                                    </div>

                                    <p id="error-message" class="text-center text-danger"></p>

                                    <div class="text-center">
                                        <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit"> Login</button>
                                    </div>


                                    <div class="d-flex align-items-center justify-content-center pb-4">
                                        <p class="mb-0 me-2">Don't have an account?</p>
                                        <a href="register.php"><button type="button" class="btn btn-primary">Register
                                            </button></a>
                                    </div>

                                </form>


                            </div>
                        </div>


                        <div class="col-lg-6 d-flex align-items-center " style="background-color:#d0efff;">
                        <div class="text-black">
                                <div class="text-center">
                                <h2 class="mb-4">CONNECTING YOU TO ENERGY <img src="images/electricbolt.png" style="width: 40px;"
                                                                               alt="logo"></h2>
                                </div>
                                <p> Borrow my charger is aimed at allowing home-owners with an electric vehicle (EV)
                                    charging point to offer it out for paid usage by other EV owners to charge their car
                                </p>
                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>
    </div>
</section>

<script src="js/index.js"></script>

<?php require('template/footer.phtml') ?>




