


    <footer class="sticky-bottom" style="background-color: #03254c;">
            <p style="color:#ffffff;" class="text-center"> © Yusra Kabir 2022 - Web-site development using the MVC design pattern
                and the Bootstrap CSS framework</p>
    </footer>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous">
</script>

