<?php session_start(); ?> <!--initiating session variables to maintain state-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <link href="/css/my-style.css" rel="stylesheet">

    <title>Borrow My Charger </title>
</head>



<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #03254c;">
    <div class="container-fluid">

        <a class="navbar-brand " <?php if (isset($_SESSION["email"])) { ?>href="home.php" <?php } ?>>Borrow My Charger</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <?php if (isset($_SESSION["email"])) { ?><a class="nav-link" href="Assessment%20Grid.pdf" download>Assessment Grid</a><?php } ?>
                </li>
            </ul>
        </div>

        <!--displaying profile menu when user is logged in-->
        <?php if (isset($_SESSION["email"])) { ?>

            <div>
                <ul class="navbar-nav ml-auto ">
                    <li class=" dropdown ms-auto">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img src="<?php echo $_SESSION["avatar"];?>" alt="avatar" width="45" height="36"></a>
                        <div class="dropdown-menu dropdown-menu-end">
                            <a href="profile.php" class="dropdown-item">Profile</a>
                            <a href="logout.php" class="dropdown-item">Logout</a>
                    </li>
                </ul>
            </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>

        <?php } ?>
</nav>







